// <auto-generated />
using System;
using Bookshelf.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookshelf.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookshelfDbContext))]
    partial class BookshelfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookshelf.Domain.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_name");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("archive")
                        .HasColumnName("catalog_state");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("ProviderBookKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_book_key");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_code");

                    b.Property<int?>("PublishYear")
                        .HasColumnType("integer")
                        .HasColumnName("publish_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OriginalTitle")
                        .HasDatabaseName("ix_books_original_title");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_books_title");

                    b.HasIndex("ProviderCode", "ProviderBookKey")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("book_authors", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.BookMediaAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("DownloadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at_utc");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("jackett")
                        .HasColumnName("source_provider");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("available")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "MediaType")
                        .IsUnique();

                    b.ToTable("book_media_assets", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.DownloadJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalJobId")
                        .HasColumnType("text")
                        .HasColumnName("external_job_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FirstNotFoundAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_not_found_at_utc");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TorrentMagnet")
                        .HasColumnType("text")
                        .HasColumnName("torrent_magnet");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("ux_active_download_per_user_book_type")
                        .HasFilter("status IN ('queued', 'downloading')");

                    b.HasIndex("UserId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_download_jobs_user_status_time");

                    b.ToTable("download_jobs", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.HistoryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("EventAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("PositionRef")
                        .HasColumnType("text")
                        .HasColumnName("position_ref");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "EventAtUtc")
                        .HasDatabaseName("ix_history_user_time");

                    b.ToTable("history_events", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.ProgressSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("PositionRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_ref");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId")
                        .HasDatabaseName("ix_progress_user_book");

                    b.HasIndex("UserId", "BookId", "MediaType")
                        .IsUnique();

                    b.ToTable("progress_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_progress_snapshots_progress_percent", "progress_percent >= 0 AND progress_percent <= 100");
                        });
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_code");

                    b.Property<string>("ProviderSeriesKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_series_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCode", "ProviderSeriesKey")
                        .IsUnique();

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.SeriesBook", b =>
                {
                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<int>("SeriesOrder")
                        .HasColumnType("integer")
                        .HasColumnName("series_order");

                    b.HasKey("SeriesId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("SeriesId", "SeriesOrder")
                        .IsUnique();

                    b.ToTable("series_books", null, t =>
                        {
                            t.HasCheckConstraint("ck_series_books_series_order", "series_order > 0");
                        });
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Shelf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("shelves", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.ShelfBook", b =>
                {
                    b.Property<long>("ShelfId")
                        .HasColumnType("bigint")
                        .HasColumnName("shelf_id");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ShelfId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("shelf_books", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.BookMediaAsset", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany("MediaAssets")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.DownloadJob", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.User", "User")
                        .WithMany("DownloadJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.HistoryEvent", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.User", "User")
                        .WithMany("HistoryEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.ProgressSnapshot", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.User", "User")
                        .WithMany("ProgressSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.SeriesBook", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany("SeriesBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.Series", "Series")
                        .WithMany("SeriesBooks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Shelf", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.User", "User")
                        .WithMany("Shelves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.ShelfBook", b =>
                {
                    b.HasOne("Bookshelf.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookshelf.Domain.Entities.Shelf", "Shelf")
                        .WithMany("ShelfBooks")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("MediaAssets");

                    b.Navigation("SeriesBooks");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Series", b =>
                {
                    b.Navigation("SeriesBooks");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.Shelf", b =>
                {
                    b.Navigation("ShelfBooks");
                });

            modelBuilder.Entity("Bookshelf.Domain.Entities.User", b =>
                {
                    b.Navigation("DownloadJobs");

                    b.Navigation("HistoryEvents");

                    b.Navigation("ProgressSnapshots");

                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
