name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore solution
        run: |
          dotnet restore Bookshelf.slnx

      - name: Build solution
        run: |
          dotnet build Bookshelf.slnx --no-restore -m:1

      - name: Test
        run: |
          dotnet test tests/Bookshelf.Domain.Tests/Bookshelf.Domain.Tests.csproj --no-restore --no-build
          dotnet test tests/Bookshelf.Application.Tests/Bookshelf.Application.Tests.csproj --no-restore --no-build
          dotnet test tests/Bookshelf.Infrastructure.Tests/Bookshelf.Infrastructure.Tests.csproj --no-restore --no-build
          dotnet test tests/Bookshelf.Api.Tests/Bookshelf.Api.Tests.csproj --no-restore --no-build
